//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MaMonAn { get; set; }
        public string TenMonAn { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public string Anh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
